# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ff47fc9ee66dc36271b4b11ba199d9466a89c548807e15f1676cd50b6b7ac603e398d81dbf569302adc976aabd911285f117c0ed195ba55675a147c6ac0886e

test:
  secret_key_base: dd46341c045282bf9ef30458f1fc6dc6f64ff1d854424ad7ad878ae95c51902ded8596bf2955292d6004b4b44836328f2eb458dcc5ecf09dba93b9d40c689c9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
